<div style="padding:30px; color: white; background-color: #0071CD">
<center>
<img src="img/logoub.jpeg">
<center>
<p>
<h1>Algorítmica Avanzada</h1>
<h2>Problemas 3.B - Programación Dinámica </h2>
</center>
</p>
</div>

<div class="alert alert-danger" style="width:95%; margin:0 auto; padding">
A la hora de crear las matrices de programación dinámica podéis emplear diversas estructuras de datos. La lista de listas puede ser una buena opción, pero existen librerías como NumPy que hacen una mejor gestión de las matrices.

Podéis consultar aquí la documentación: https://docs.scipy.org/doc/numpy/reference/

<div class="alert alert-success" style="width:90%; margin:0 auto;">

  <h2><p>3 - Distancia de edición</p></h2>
  
  <p> Dadas dos cadenas S1 y S2, este algoritmo trata de encontrar la "distancia" entre ellas. Basamos la distancia en el número de transformaciones necesarias para convertir la cadena S1 en la cadena S2 (o viceversa). Se consideran tres transformaciones distintas: inserción, eliminación y sustitución. Los costes de cada operación serán parámetros de la función.</p>
  
  <img src='img/min_Edit_Distance_DP_Table.png' width="50%">
  
Además, se os pide que reconstruyáis el conjunto de operaciones que realizar sobre la primera palabra (<i>relevant</i>) para convertirla en la segunda (<i>elephant</i>). En el ejemplo de la imagen (donde los costes de las operaciones es 1 para todas):
<ul>
    <li> Eliminar 'R' en la posición 0.           $('D','R',0)$</li>
    <li> Insertar 'P' en la posición 4.           $('I','P',4)$</li>
    <li> Substituir 'V' por 'H' en la posición 5.            $('R',('V', 'H'),4)$ </li>
    <li> ........ El coste total de edición es: 3 </li>
</ul>

** Nota: Vuestro algoritmo podría encontrar otro conjunto de operaciones distinto a este pero con el mismo coste de edición.

In [1]:
import numpy as np
'''
Implementa aquí el algoritmo de distancia de edición
'''
def distancia_edicion(s1,s2,ci=2,cd=2,cr=1):# ci = insretion cost, cd = delete cost, cr = replacement cost
    
    m = np.zeros((len(s1)+1,len(s2)+1))
    
    for i in range(0,len(s1)+1):
        m[i][0] = i*ci
    for j in range(0,len(s2)+1):
        m[0][j] = j*ci
        
    for i in range(1,len(s1)+1):
        for j in range(1,len(s2)+1):
            if(s1[i-1] == s2[j-1]):
                m[i][j] = m[i-1][j-1] #No habra edicion, misma letra
            else:
                m[i][j] = min(m[i-1,j]+cd,m[i,j-1]+ci,m[i-1,j-1]+cr) #3 posiciones adyacentes
    
    return m

In [9]:
print(distancia_edicion('relevant','elephant'))
print(distancia_edicion('surgery', 'survey'))
print(distancia_edicion('abcde', 'vwxyz'))
print(distancia_edicion('cristina', 'marta'))

[[ 0.  2.  4.  6.  8. 10. 12. 14. 16.]
 [ 2.  1.  3.  5.  7.  9. 11. 13. 15.]
 [ 4.  2.  2.  3.  5.  7.  9. 11. 13.]
 [ 6.  4.  2.  3.  4.  6.  8. 10. 12.]
 [ 8.  6.  4.  2.  4.  5.  7.  9. 11.]
 [10.  8.  6.  4.  3.  5.  6.  8. 10.]
 [12. 10.  8.  6.  5.  4.  5.  7.  9.]
 [14. 12. 10.  8.  7.  6.  5.  5.  7.]
 [16. 14. 12. 10.  9.  8.  7.  6.  5.]]
[[ 0.  2.  4.  6.  8. 10. 12.]
 [ 2.  0.  2.  4.  6.  8. 10.]
 [ 4.  2.  0.  2.  4.  6.  8.]
 [ 6.  4.  2.  0.  2.  4.  6.]
 [ 8.  6.  4.  2.  1.  3.  5.]
 [10.  8.  6.  4.  3.  1.  3.]
 [12. 10.  8.  6.  5.  3.  2.]
 [14. 12. 10.  8.  7.  5.  3.]]
[[ 0.  2.  4.  6.  8. 10.]
 [ 2.  1.  3.  5.  7.  9.]
 [ 4.  3.  2.  4.  6.  8.]
 [ 6.  5.  4.  3.  5.  7.]
 [ 8.  7.  6.  5.  4.  6.]
 [10.  9.  8.  7.  6.  5.]]
[[ 0.  2.  4.  6.  8. 10.]
 [ 2.  1.  3.  5.  7.  9.]
 [ 4.  3.  2.  3.  5.  7.]
 [ 6.  5.  4.  3.  4.  6.]
 [ 8.  7.  6.  5.  4.  5.]
 [10.  9.  8.  7.  5.  5.]
 [12. 11. 10.  9.  7.  6.]
 [14. 13. 12. 11.  9.  8.]
 [16. 15. 13. 13. 11

<div class="alert alert-warning" style="width:80%; margin:0 auto; padding">
<center><p><h3> Cuestiones</h3></p> </center> </div>

<ul>
    <li>Analiza la complejidad del algoritmo.</li>
</ul>

<div class="alert alert-success" style="width:90%; margin:0 auto;">

  <h2><p>4 - Torres de Hanoi</p></h2>
  
  <p>Se plantea un escenario con 3 torres y una serie de discos de diferentes tamaños. Buscamos mover todos los discos de una torre origen a otra destino empleando la torre intermedia como soporte. Siempre deberán cumplirse las siguientes condiciones:
<ul>
    <li> Solo podemos mover un disco a cada vez. </li>
    <li> Un movimiento de disco consiste en coger el disco superior de una de las torres y colocarlo en la cima de otra de las torres. </li>
    <li> Un disco nunca podrá estar sobre otro disco de menor tamaño. </li>
</ul>

Podéis ver aquí un ejemplo animado de Hanoi con 4 discos en la que queremos mover todos los discos desde la torre izquierda a la derecha.
<center><img src="img/hanoi.gif"></center>

Para más ejemplos y experimentación, tenéis disponible el juego online: https://www.mathsisfun.com/games/towerofhanoi.html
    
Se os pide que implementéis la solución de Programación Dinámica al problema de las torres de Hanoi para calcular el número mínimo de movimientos necesarios para mover $D$ discos de la torre $t_o$ a la torre $t_d$.

Además, se os pide que devolváis una lista de tuplas con la forma $(t_i,t_j)$ que simboliza mover el disco que se encuentra más arriba de la torre $i$ a la cima de la torre $j$.
Por ejemplo, para 3 discos, los movimientos serían:
[(0, 2), (0, 1), (2, 1), (0, 2), (1, 0), (1, 2), (0, 2)]
</p>
  

In [1]:
import numpy as np
def exclude(a,b):
    return 3-(a+b)

def dynamic_hanoi(D,t0=0,t1=2):
    #Create matrix
    num_moves= np.zeros((D,3,3),dtype=np.integer)
    movements= dict()
    
    for i in range(3):
        for j in range(3):
            num_moves[0,i,j] = 1 if i!=j else 0
            
    for d in range(1,D):
        for i in range(3):
            for j in range(3):
                if i!=j:
                    eTower = exclude(i,j)
                    num_moves[d,i,j] = num_moves[d-1,i,eTower]+num_moves[0,i,j] + num_moves[d-1,eTower,j]
                    movements[(d,i,j)] = [(d-1,i,eTower),(0,i,j),(d-1,eTower,j)]
        
    def get_move_ordering(move):
        moves =[]
        if move[0] == 1:
            return [(m[1],m[2]) for m in movements[move]]
        else:
            for i in range(3):
                next_move= movements[move][i]
                if next_move[0] == 0:
                    moves.append((next_move[-2],next_move[-1]))
                else:
                    for n in get_move_ordering(next_move):
                        moves.append(n)
            return moves

    current_move = (D-1,t0,t1)
    num_moves= num_moves[current_move]
    moves = get_move_ordering(current_move)
    
    return num_moves ,moves

In [2]:
# Prueba tu algoritmo
# Mover n discos debería resultar en (2^n -1) movimientos

print(dynamic_hanoi(3))
print(dynamic_hanoi(4))
print(dynamic_hanoi(5))
print(dynamic_hanoi(6))
print(dynamic_hanoi(7))

(7, [(0, 2), (0, 1), (2, 1), (0, 2), (1, 0), (1, 2), (0, 2)])
(15, [(0, 1), (0, 2), (1, 2), (0, 1), (2, 0), (2, 1), (0, 1), (0, 2), (1, 2), (1, 0), (2, 0), (1, 2), (0, 1), (0, 2), (1, 2)])
(31, [(0, 2), (0, 1), (2, 1), (0, 2), (1, 0), (1, 2), (0, 2), (0, 1), (2, 1), (2, 0), (1, 0), (2, 1), (0, 2), (0, 1), (2, 1), (0, 2), (1, 0), (1, 2), (0, 2), (1, 0), (2, 1), (2, 0), (1, 0), (1, 2), (0, 2), (0, 1), (2, 1), (0, 2), (1, 0), (1, 2), (0, 2)])
(63, [(0, 1), (0, 2), (1, 2), (0, 1), (2, 0), (2, 1), (0, 1), (0, 2), (1, 2), (1, 0), (2, 0), (1, 2), (0, 1), (0, 2), (1, 2), (0, 1), (2, 0), (2, 1), (0, 1), (2, 0), (1, 2), (1, 0), (2, 0), (2, 1), (0, 1), (0, 2), (1, 2), (0, 1), (2, 0), (2, 1), (0, 1), (0, 2), (1, 2), (1, 0), (2, 0), (1, 2), (0, 1), (0, 2), (1, 2), (1, 0), (2, 0), (2, 1), (0, 1), (2, 0), (1, 2), (1, 0), (2, 0), (1, 2), (0, 1), (0, 2), (1, 2), (0, 1), (2, 0), (2, 1), (0, 1), (0, 2), (1, 2), (1, 0), (2, 0), (1, 2), (0, 1), (0, 2), (1, 2)])
(127, [(0, 2), (0, 1), (2, 1), (0, 2), (1, 0)

<div class="alert alert-warning" style="width:80%; margin:0 auto; padding">
<center><p><h3> Cuestiones</h3></p> </center> </div>

<ul>
    <li>Analiza la complejidad del algoritmo.</li>
</ul>